#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
      use_rest:       Always
  vars_files:
    - ../global_nas.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create qtree on primary SVM
    na_ontap_qtree:
      state:                 present
      name:                  nfs_01
      vserver:               "{{ PRI_SVM }}"
      flexvol_name:          "{{ PRI_SVM }}_nfs_01"
      security_style:        unix
      <<: *input

  - name: Create export policy
    na_ontap_export_policy_rule:
      state: present
      name: default
      vserver: "{{ PRI_SVM }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: any
      protocol: nfs3
      super_user_security: any
      anonymous_user_id: 65534
      allow_suid: true
      <<: *input